#!/usr/bin/env node

const _ = require('lodash');
const fs = require('fs');
const glob = require('glob');
const hjson = require('hjson');
const Q = require('q');
const path = require('path');
const writeFile = require('./writeFile');

const generateHTML = function(project) {
  if (['angularjs', 'react'].indexOf(project) === -1) throw new Error('Unsupported project : ' + project);

  const deferred = Q.defer();
  const template = _.template(String(fs.readFileSync('e2e/templates/' + project + '/single.html')));

  glob('e2e/test_cases/*.hjson', (er, files) => {
    files.forEach(file => {
      const name = path.basename(file, path.extname(file));
      var data = hjson.parse(fs.readFileSync(file, 'utf8'));

      writeFile('.tmp/test/e2e/' + project + '/' + name + '.html', template({data, name}));
    });

    deferred.resolve();
  });

  return deferred.promise;
};

const generateAll = function() {
  return Q.all([generateHTML('react'), generateHTML('angularjs')]);
};

if (require.main === module) {
  generateAll();
} else {
  module.exports = generateAll;
}
