#!/usr/bin/env node

const express = require('express');
const serveStatic = require('serve-static');

const serve = () => {
  const app = express()

  app.use(serveStatic('.tmp'));
  app.use(serveStatic('node_modules'));
  app.listen(1234, () => {
    console.log('Listening on port 1234...');
  });
};

if (require.main === module) {
  serve();
} else {
  module.exports = serve;
}


